
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // Lookup simples (não usa o helper `env()`, que lança erro se a variável
    // não existir) — `prisma generate` não precisa de conexão real, só do
    // schema, então isso não deve travar o build antes da env var existir.
    url: process.env.DATABASE_URL ?? "",
  },
});
